#pragma once

#include <map>
#include <string>
#include "bakkesmod/wrappers/matchmakingwrapper.h"

// originally in the bakkesmodsdk under wrappers/matchmakingwrapper
// this hasn't been updated in a while.

// this would be the updated list.
enum class PlaylistId {
      Unknown                 = -1337,
      Casual                  = 0,
      Duel                    = 1,
      Doubles                 = 2,
      Standard                = 3,
      Quads                   = 4,
      PrivateMatch            = 6,
      Season                  = 7,
      OfflineSplitscreen      = 8,
      Training                = 9,
      RankedSoloDuel          = 10,
      RankedTeamDoubles       = 11,
      RankedStandard          = 13,
      MutatorMashup           = 14,
      SnowDayPromotion        = 15,
      Experimental            = 16,
      BasketballDoubles       = 17,
      Rumble                  = 18,
      Workshop                = 19,
      UGCTrainingEditor       = 20,
      UGCTraining             = 21,
      Tournament              = 22,
      Breakout                = 23,
      LANMatch                = 24,
      TenthAnniversary        = 25,  // not in codered log?
      FaceIt                  = 26,
      RankedBasketballDoubles = 27,
      RankedRumble            = 28,
      RankedBreakout          = 29,
      RankedSnowDay           = 30,
      HauntedBall             = 31,
      BeachBall               = 32,
      Rugby                   = 33,
      AutoTournament          = 34,
      RocketLabs              = 35,
      RumShot                 = 37,
      GodBall                 = 38,
      CoopVsAI                = 40,
      BoomerBall              = 41,
      GodBallDoubles          = 43,
      SpecialSnowDay          = 44,
      Football                = 46,
      Cubic                   = 47,
      TacticalRumble          = 48,
      SpringLoaded            = 49,
      SpeedDemon              = 50,
      RumbleBM                = 52,
      Knockout                = 54,
      Thirdwheel              = 55,
      RankedQuads             = 61,
      MagnusFutball           = 62,
      GodBallSpooky           = 64,
      GodBallHaunted          = 65,
      GodBallRicochet         = 66,
      CubicSpooky             = 67,
      GForceFrenzy            = 68,
      RumShotDoubles          = 70,
      Territory               = 72,
      OnlineFreeplay          = 73,
      TerritoryDoubles        = 74,
      GodballTerritory        = 75,
      GodballTerritoryDoubles = 76,
      NonStandardSoccar       = 77,
      SnowdayTerritory        = 79,
      RunItBack               = 80,
      CarWars                 = 81,
      PizzaParty              = 82,
      PushThePuck             = 83,
      Possession              = 84,
      FCShowdown              = 86,
      Sacrifice               = 87,
      JumpJam                 = 88,
      SonicRush               = 89,
      UpToNoGood = 90,
};

// fuck clang-lint/tidy "ODR" bullshit.
namespace bm_helper {
std::map<PlaylistId, std::string> playlist_ids_str = {
      {                PlaylistId::Unknown,                 "Unknown"},
      {                 PlaylistId::Casual,                  "Casual"},
      {                   PlaylistId::Duel,                    "Duel"},
      {                PlaylistId::Doubles,                 "Doubles"},
      {               PlaylistId::Standard,                "Standard"},
      {                  PlaylistId::Quads,                   "Quads"},
      {           PlaylistId::PrivateMatch,            "PrivateMatch"},
      {                 PlaylistId::Season,                  "Season"},
      {     PlaylistId::OfflineSplitscreen,      "OfflineSplitscreen"},
      {               PlaylistId::Training,                "Training"},
      {         PlaylistId::RankedSoloDuel,          "RankedSoloDuel"},
      {      PlaylistId::RankedTeamDoubles,       "RankedTeamDoubles"},
      {         PlaylistId::RankedStandard,          "RankedStandard"},
      {          PlaylistId::MutatorMashup,           "MutatorMashup"},
      {       PlaylistId::SnowDayPromotion,        "SnowDayPromotion"},
      {           PlaylistId::Experimental,            "Experimental"},
      {      PlaylistId::BasketballDoubles,       "BasketballDoubles"},
      {                 PlaylistId::Rumble,                  "Rumble"},
      {               PlaylistId::Workshop,                "Workshop"},
      {      PlaylistId::UGCTrainingEditor,       "UGCTrainingEditor"},
      {            PlaylistId::UGCTraining,             "UGCTraining"},
      {             PlaylistId::Tournament,              "Tournament"},
      {               PlaylistId::Breakout,                "Breakout"},
      {               PlaylistId::LANMatch,                "LANMatch"},
      {       PlaylistId::TenthAnniversary,        "TenthAnniversary"},
      {                 PlaylistId::FaceIt,                  "FaceIt"},
      {PlaylistId::RankedBasketballDoubles, "RankedBasketballDoubles"},
      {           PlaylistId::RankedRumble,            "RankedRumble"},
      {         PlaylistId::RankedBreakout,          "RankedBreakout"},
      {          PlaylistId::RankedSnowDay,           "RankedSnowDay"},
      {            PlaylistId::HauntedBall,             "HauntedBall"},
      {              PlaylistId::BeachBall,               "BeachBall"},
      {                  PlaylistId::Rugby,                   "Rugby"},
      {         PlaylistId::AutoTournament,          "AutoTournament"},
      {             PlaylistId::RocketLabs,              "RocketLabs"},
      {                PlaylistId::RumShot,                 "RumShot"},
      {                PlaylistId::GodBall,                 "GodBall"},
      {               PlaylistId::CoopVsAI,                "CoopVsAI"},
      {             PlaylistId::BoomerBall,              "BoomerBall"},
      {         PlaylistId::GodBallDoubles,          "GodBallDoubles"},
      {         PlaylistId::SpecialSnowDay,          "SpecialSnowDay"},
      {               PlaylistId::Football,                "Football"},
      {                  PlaylistId::Cubic,                   "Cubic"},
      {         PlaylistId::TacticalRumble,          "TacticalRumble"},
      {           PlaylistId::SpringLoaded,            "SpringLoaded"},
      {             PlaylistId::SpeedDemon,              "SpeedDemon"},
      {               PlaylistId::RumbleBM,                "RumbleBM"},
      {               PlaylistId::Knockout,                "Knockout"},
      {             PlaylistId::Thirdwheel,              "Thirdwheel"},
      {            PlaylistId::RankedQuads,             "RankedQuads"},
      {          PlaylistId::MagnusFutball,           "MagnusFutball"},
      {          PlaylistId::GodBallSpooky,           "GodBallSpooky"},
      {         PlaylistId::GodBallHaunted,          "GodBallHaunted"},
      {        PlaylistId::GodBallRicochet,         "GodBallRicochet"},
      {            PlaylistId::CubicSpooky,             "CubicSpooky"},
      {           PlaylistId::GForceFrenzy,            "GForceFrenzy"},
      {         PlaylistId::RumShotDoubles,          "RumShotDoubles"},
      {              PlaylistId::Territory,               "Territory"},
      {         PlaylistId::OnlineFreeplay,          "OnlineFreeplay"},
      {       PlaylistId::TerritoryDoubles,        "TerritoryDoubles"},
      {       PlaylistId::GodballTerritory,        "GodballTerritory"},
      {PlaylistId::GodballTerritoryDoubles, "GodballTerritoryDoubles"},
      {       PlaylistId::SnowdayTerritory,        "SnowdayTerritory"},
      {              PlaylistId::RunItBack,               "RunItBack"},
      {                PlaylistId::CarWars,                 "CarWars"},
      {             PlaylistId::PizzaParty,              "PizzaParty"},
      {            PlaylistId::PushThePuck,             "PushThePuck"},
      {             PlaylistId::Possession,              "Possession"},
      {             PlaylistId::FCShowdown,              "FCShowdown"},
      {              PlaylistId::Sacrifice,               "Sacrifice"},
      {                PlaylistId::JumpJam,                 "JumpJam"},
      {              PlaylistId::SonicRush,               "SonicRush"},
            {              PlaylistId::UpToNoGood,               "UpToNoGood"},
};

std::map<std::string, PlaylistId> playlist_str_ids = {
      {                "Unknown",                 PlaylistId::Unknown},
      {                 "Casual",                  PlaylistId::Casual},
      {                   "Duel",                    PlaylistId::Duel},
      {                "Doubles",                 PlaylistId::Doubles},
      {               "Standard",                PlaylistId::Standard},
      {                  "Quads",                   PlaylistId::Quads},
      {           "PrivateMatch",            PlaylistId::PrivateMatch},
      {                 "Season",                  PlaylistId::Season},
      {     "OfflineSplitscreen",      PlaylistId::OfflineSplitscreen},
      {               "Training",                PlaylistId::Training},
      {         "RankedSoloDuel",          PlaylistId::RankedSoloDuel},
      {      "RankedTeamDoubles",       PlaylistId::RankedTeamDoubles},
      {         "RankedStandard",          PlaylistId::RankedStandard},
      {          "MutatorMashup",           PlaylistId::MutatorMashup},
      {       "SnowDayPromotion",        PlaylistId::SnowDayPromotion},
      {           "Experimental",            PlaylistId::Experimental},
      {      "BasketballDoubles",       PlaylistId::BasketballDoubles},
      {                 "Rumble",                  PlaylistId::Rumble},
      {               "Workshop",                PlaylistId::Workshop},
      {      "UGCTrainingEditor",       PlaylistId::UGCTrainingEditor},
      {            "UGCTraining",             PlaylistId::UGCTraining},
      {             "Tournament",              PlaylistId::Tournament},
      {               "Breakout",                PlaylistId::Breakout},
      {               "LANMatch",                PlaylistId::LANMatch},
      {       "TenthAnniversary",        PlaylistId::TenthAnniversary},
      {                 "FaceIt",                  PlaylistId::FaceIt},
      {"RankedBasketballDoubles", PlaylistId::RankedBasketballDoubles},
      {           "RankedRumble",            PlaylistId::RankedRumble},
      {         "RankedBreakout",          PlaylistId::RankedBreakout},
      {          "RankedSnowDay",           PlaylistId::RankedSnowDay},
      {            "HauntedBall",             PlaylistId::HauntedBall},
      {              "BeachBall",               PlaylistId::BeachBall},
      {                  "Rugby",                   PlaylistId::Rugby},
      {         "AutoTournament",          PlaylistId::AutoTournament},
      {             "RocketLabs",              PlaylistId::RocketLabs},
      {                "RumShot",                 PlaylistId::RumShot},
      {                "GodBall",                 PlaylistId::GodBall},
      {               "CoopVsAI",                PlaylistId::CoopVsAI},
      {             "BoomerBall",              PlaylistId::BoomerBall},
      {         "GodBallDoubles",          PlaylistId::GodBallDoubles},
      {         "SpecialSnowDay",          PlaylistId::SpecialSnowDay},
      {               "Football",                PlaylistId::Football},
      {                  "Cubic",                   PlaylistId::Cubic},
      {         "TacticalRumble",          PlaylistId::TacticalRumble},
      {           "SpringLoaded",            PlaylistId::SpringLoaded},
      {             "SpeedDemon",              PlaylistId::SpeedDemon},
      {               "RumbleBM",                PlaylistId::RumbleBM},
      {               "Knockout",                PlaylistId::Knockout},
      {             "Thirdwheel",              PlaylistId::Thirdwheel},
      {            "RankedQuads",             PlaylistId::RankedQuads},
      {          "MagnusFutball",           PlaylistId::MagnusFutball},
      {          "GodBallSpooky",           PlaylistId::GodBallSpooky},
      {         "GodBallHaunted",          PlaylistId::GodBallHaunted},
      {        "GodBallRicochet",         PlaylistId::GodBallRicochet},
      {            "CubicSpooky",             PlaylistId::CubicSpooky},
      {           "GForceFrenzy",            PlaylistId::GForceFrenzy},
      {         "RumShotDoubles",          PlaylistId::RumShotDoubles},
      {              "Territory",               PlaylistId::Territory},
      {         "OnlineFreeplay",          PlaylistId::OnlineFreeplay},
      {       "TerritoryDoubles",        PlaylistId::TerritoryDoubles},
      {       "GodballTerritory",        PlaylistId::GodballTerritory},
      {"GodballTerritoryDoubles", PlaylistId::GodballTerritoryDoubles},
      {       "SnowdayTerritory",        PlaylistId::SnowdayTerritory},
      {              "RunItBack",               PlaylistId::RunItBack},
      {                "CarWars",                 PlaylistId::CarWars},
      {             "PizzaParty",              PlaylistId::PizzaParty},
      {            "PushThePuck",             PlaylistId::PushThePuck},
      {             "Possession",              PlaylistId::Possession},
      {             "FCShowdown",              PlaylistId::FCShowdown},
      {              "Sacrifice",               PlaylistId::Sacrifice},
      {                "JumpJam",                 PlaylistId::JumpJam},
      {              "SonicRush",               PlaylistId::SonicRush},
      {              "UpToNoGood",               PlaylistId::UpToNoGood},
};

// More familiar names for playlist ids
std::map<PlaylistId, std::string> playlist_ids_str_spaced = {
      {                PlaylistId::Unknown,                       "Unknown"},
      {                 PlaylistId::Casual,                        "Casual"},
      {                   PlaylistId::Duel,                   "Casual Duel"},
      {                PlaylistId::Doubles,                "Casual Doubles"},
      {               PlaylistId::Standard,               "Casual Standard"},
      {                  PlaylistId::Quads,                  "Casual Quads"},
      {           PlaylistId::PrivateMatch,                 "Private Match"},
      {                 PlaylistId::Season,                "Offline Season"},
      {     PlaylistId::OfflineSplitscreen,                    "Exhibition"},
      {               PlaylistId::Training,                     "Free Play"},
      {         PlaylistId::RankedSoloDuel,                   "Ranked Duel"},
      {      PlaylistId::RankedTeamDoubles,                "Ranked Doubles"},
      {         PlaylistId::RankedStandard,               "Ranked Standard"},
      {          PlaylistId::MutatorMashup,                "Mutator Mashup"},
      {       PlaylistId::SnowDayPromotion,               "Casual Snow Day"},
      {           PlaylistId::Experimental,                   "Rocket Labs"},
      {      PlaylistId::BasketballDoubles,                  "Casual Hoops"},
      {                 PlaylistId::Rumble,                 "Casual Rumble"},
      {               PlaylistId::Workshop,                      "Workshop"},
      {      PlaylistId::UGCTrainingEditor,        "Custom Training Editor"},
      {            PlaylistId::UGCTraining,               "Custom Training"},
      {             PlaylistId::Tournament,             "Custom Tournament"},
      {               PlaylistId::Breakout,               "Casual Dropshot"},
      {               PlaylistId::LANMatch,                     "LAN Match"},
      {       PlaylistId::TenthAnniversary,             "Tenth Anniversary"},
      {                 PlaylistId::FaceIt,                "External Match"},
      {PlaylistId::RankedBasketballDoubles,                  "Ranked Hoops"},
      {           PlaylistId::RankedRumble,                 "Ranked Rumble"},
      {         PlaylistId::RankedBreakout,               "Ranked Dropshot"},
      {          PlaylistId::RankedSnowDay,               "Ranked Snow Day"},
      {            PlaylistId::HauntedBall,                    "Ghost Hunt"},
      {              PlaylistId::BeachBall,                    "Beach Ball"},
      {                  PlaylistId::Rugby,                    "Spike Rush"},
      {         PlaylistId::AutoTournament,                    "Tournament"},
      {             PlaylistId::RocketLabs,                "Rocket Labs(2)"},
      {                PlaylistId::RumShot,               "Dropshot Rumble"},
      {                PlaylistId::GodBall,                    "Heatseeker"},
      {               PlaylistId::CoopVsAI,                    "Coop Vs AI"},
      {             PlaylistId::BoomerBall,                   "Boomer Ball"},
      {         PlaylistId::GodBallDoubles,            "Heatseeker Doubles"},
      {         PlaylistId::SpecialSnowDay,              "Winter Breakaway"},
      {               PlaylistId::Football,                      "Gridiron"},
      {                  PlaylistId::Cubic,                    "Super Cube"},
      {         PlaylistId::TacticalRumble,               "Tactical Rumble"},
      {           PlaylistId::SpringLoaded,                 "Spring Loaded"},
      {             PlaylistId::SpeedDemon,                   "Speed Demon"},
      {               PlaylistId::RumbleBM,            "Gotham City Rumble"},
      {               PlaylistId::Knockout,                      "Knockout"},
      {             PlaylistId::Thirdwheel,  "confidential_thirdwheel_test"},
      {            PlaylistId::RankedQuads,                  "Ranked Quads"},
      {          PlaylistId::MagnusFutball,              "Nike FC Showdown"},
      {          PlaylistId::GodBallSpooky,            "Haunted Heatseeker"},
      {         PlaylistId::GodBallHaunted,         "Haunted Heatseeker(2)"},
      {        PlaylistId::GodBallRicochet,           "Heatseeker Ricochet"},
      {            PlaylistId::CubicSpooky,                   "Spooky Cube"},
      {           PlaylistId::GForceFrenzy,                "G-Force Frenzy"},
      {         PlaylistId::RumShotDoubles,       "Dropshot Rumble Doubles"},
      {              PlaylistId::Territory,                    "Split Shot"},
      {         PlaylistId::OnlineFreeplay,              "Online Free Play"},
      {       PlaylistId::TerritoryDoubles,            "Split Shot Doubles"},
      {       PlaylistId::GodballTerritory,         "Split Shot Heatseeker"},
      {PlaylistId::GodballTerritoryDoubles, "Split Shot Heatseeker Doubles"},
      {       PlaylistId::SnowdayTerritory,           "Split Shot Snow Day"},
      {              PlaylistId::RunItBack,                   "Run It Back"},
      {                PlaylistId::CarWars,                      "Car Wars"},
      {             PlaylistId::PizzaParty,                   "Pizza Party"},
      {            PlaylistId::PushThePuck,                 "Push The Puck"},
      {             PlaylistId::Possession,             "Possession Rumble"},
      {             PlaylistId::FCShowdown,          "Adidas Soccar Strike"},
      {              PlaylistId::Sacrifice,               "Demolition Duel"},
      {                PlaylistId::JumpJam,                      "Jump Jam"},
      {              PlaylistId::SonicRush,                    "Sonic Spin"},
            {              PlaylistId::UpToNoGood,                    "Up To No Good"},
};

std::map<std::string, std::vector<PlaylistId>> playlist_categories = {
      {       "Casual",
       {
       PlaylistId::Duel,
       PlaylistId::Doubles,
       PlaylistId::Standard,
       PlaylistId::Quads,
       PlaylistId::Rumble,
       PlaylistId::SnowDayPromotion,
       PlaylistId::BasketballDoubles,
       PlaylistId::Breakout,
       PlaylistId::MutatorMashup,
       PlaylistId::Experimental,
       PlaylistId::TenthAnniversary,
       PlaylistId::FaceIt,
       PlaylistId::HauntedBall,
       PlaylistId::BeachBall,
       PlaylistId::Rugby,
       PlaylistId::RocketLabs,
       PlaylistId::RumShot,
       PlaylistId::GodBall,
       PlaylistId::CoopVsAI,
       PlaylistId::BoomerBall,
       PlaylistId::GodBallDoubles,
       PlaylistId::SpecialSnowDay,
       PlaylistId::Football,
       PlaylistId::Cubic,
       PlaylistId::TacticalRumble,
       PlaylistId::SpringLoaded,
       PlaylistId::SpeedDemon,
       PlaylistId::RumbleBM,
       PlaylistId::Knockout,
       PlaylistId::Thirdwheel,
       PlaylistId::MagnusFutball,
       PlaylistId::GodBallSpooky,
       PlaylistId::GodBallHaunted,
       PlaylistId::GodBallRicochet,
       PlaylistId::CubicSpooky,
       PlaylistId::GForceFrenzy,
       PlaylistId::RumShotDoubles,
       PlaylistId::Territory,
       PlaylistId::TerritoryDoubles,
       PlaylistId::GodballTerritory,
       PlaylistId::GodballTerritoryDoubles,
       PlaylistId::SnowdayTerritory,
       PlaylistId::RunItBack,
       PlaylistId::CarWars,
       PlaylistId::PizzaParty,
       PlaylistId::PushThePuck,
       PlaylistId::Possession,
       PlaylistId::FCShowdown,
       PlaylistId::Sacrifice,
       PlaylistId::JumpJam,
       PlaylistId::SonicRush,
              PlaylistId::UpToNoGood,
       }                                                                                                         },
      {  "Competitive",
       {PlaylistId::RankedSoloDuel,
       PlaylistId::RankedTeamDoubles,
       PlaylistId::RankedStandard,
       PlaylistId::RankedQuads,
       PlaylistId::RankedRumble,
       PlaylistId::RankedBasketballDoubles,
       PlaylistId::RankedBreakout,
       PlaylistId::RankedSnowDay}                                                                                },
      {   "Tournament",                                      {PlaylistId::AutoTournament, PlaylistId::Tournament}},
      {     "Training",
       {PlaylistId::Training, PlaylistId::OnlineFreeplay, PlaylistId::UGCTraining, PlaylistId::UGCTrainingEditor}},
      {      "Offline",                {PlaylistId::OfflineSplitscreen, PlaylistId::Season, PlaylistId::Workshop}},
      {"Private Match",                                          {PlaylistId::PrivateMatch, PlaylistId::LANMatch}},
};

std::map<OnlinePlatform, std::string> onlineplatform_ids_str = {
      {OnlinePlatform_Unknown, "OnlinePlatform_Unknown"},
      {  OnlinePlatform_Steam,   "OnlinePlatform_Steam"},
      {    OnlinePlatform_PS4,     "OnlinePlatform_PS4"},
      {    OnlinePlatform_PS3,     "OnlinePlatform_PS3"},
      {  OnlinePlatform_Dingo,   "OnlinePlatform_Dingo"}, // xbox?
      {     OnlinePlatform_QQ,      "OnlinePlatform_QQ"},
      { OnlinePlatform_OldNNX,  "OnlinePlatform_OldNNX"},
      {    OnlinePlatform_NNX,     "OnlinePlatform_NNX"},
      { OnlinePlatform_PsyNet,  "OnlinePlatform_PsyNet"},
      {OnlinePlatform_Deleted, "OnlinePlatform_Deleted"},
      { OnlinePlatform_WeGame,  "OnlinePlatform_WeGame"},
      {   OnlinePlatform_Epic,    "OnlinePlatform_Epic"},
      {    OnlinePlatform_MAX,     "OnlinePlatform_MAX"}
};
}  // namespace bm_helper
